article_list:
    path:     /
    defaults: { _controller: ClicSapeAdminBundle:Article:list }

article_add:
    path:     /add
    defaults: { _controller: ClicSapeAdminBundle:Article:add }

article_edit:
    path:     /edit/{id}
    defaults: { _controller: ClicSapeAdminBundle:Article:edit }
    requirements:
        id: \d+

article_delete:
    path: /delete
    defaults: { _controller: ClicSapeAdminBundle:Article:delete }
    requirements:
        methods:  POST

article_filter:
    path: /filter
    defaults: { _controller: ClicSapeAdminBundle:Article:filter }