article_list:
    path:     /
    defaults: { _controller: ClicSapeAdminBundle:Article:list }

add:
    path:     /add
    defaults: { _controller: ClicSapeAdminBundle:Article:add }

edit:
    path:     /edit/{id}
    defaults: { _controller: ClicSapeAdminBundle:Article:edit }
    requirements:
        id: \d+
