category_list:
    path:     /list
    defaults: { _controller: ClicSapeAdminBundle:Category:list }

category_add:
    path:     /add
    defaults: { _controller: ClicSapeAdminBundle:Category:add }

category_edit:
    path:     /edit/{id}
    defaults: { _controller: ClicSapeAdminBundle:Category:edit }
    requirements:
        id: \d+
