category_list:
    path:     /
    defaults: { _controller: ClicSapeAdminBundle:Category:list }

category_add:
    path:     /add
    defaults: { _controller: ClicSapeAdminBundle:Category:add }

category_edit:
    path:     /edit/{id}
    defaults: { _controller: ClicSapeAdminBundle:Category:edit }
    requirements:
        id: \d+

category_delete:
    path: /delete
    defaults: { _controller: ClicSapeAdminBundle:Category:delete }
    requirements:
        methods:  POST
        
category_all:
    path: /all
    defaults: { _controller: ClicSapeAdminBundle:Category:all }
    