groupsize_list:
    path:     /
    defaults: { _controller: ClicSapeAdminBundle:GroupSize:list }

groupsize_add:
    path:     /add
    defaults: { _controller: ClicSapeAdminBundle:GroupSize:add }

groupsize_edit:
    path:     /edit/{id}
    defaults: { _controller: ClicSapeAdminBundle:GroupSize:edit }
    requirements:
        id: \d+
        
groupsize_delete:
    path: /delete
    defaults: { _controller: ClicSapeAdminBundle:GroupSize:delete }
    requirements:
        methods:  POST