<?php

namespace ClicSape\Bundle\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserFbRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserFbRepository extends EntityRepository
{
}
