<?php

namespace ClicSape\Bundle\ClotheBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    public function findByFilter(QueryBuilder $queryBuilder = null, $filter, $value) {
        if($queryBuilder === null){
        $queryBuilder = $this->createQueryBuilder('a')
            ->where('a.'.$filter.' LIKE :value')
            ->setParameter('value', $value);
        } else {
            $queryBuilder->andWhere('a.'.$filter.' LIKE :value')
            ->setParameter('value', $value);
        }
        
        return $queryBuilder;
    }
    
}
