<?php

namespace ClicSape\Bundle\ClotheBundle\Entity;

use Doctrine\ORM\EntityRepository;
use ClicSape\Bundle\ClotheBundle\Entity\GroupSize;

/**
 * GroupSizeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupSizeRepository extends EntityRepository
{
    public function saveSize(GroupSize $groupSize)
    {
        
    }
    public function removeSize($id)
    {
        
    }
    public function saveSizes(GroupSize $groupSize)
    {
        
    }
}
