<?php

namespace ClicSape\Bundle\ClotheBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PickupPointRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PickupPointRepository extends EntityRepository
{
}
