<?php

namespace ClicSape\Bundle\ClotheBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SizeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SizeRepository extends EntityRepository
{
    /**
     * @param array of id
     * 
     * 
     */
    public function disabledSizes(array $ids){
        foreach($ids as $id){
            $size = $this->find($id);
            $em = $this->getEntityManager();
            if($size !== null){
                $size->setGroupSize();
                $em->flush($size);
            } else {
                throw $this->createNotFoundException('No Size found for id : '.$id);
            }
        }        
    }
}
