clic_sape_admin:
    resource: "@ClicSapeAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

clic_sape:
    resource: "@ClicSapeClotheBundle/Resources/config/routing.yml"
    prefix:   /

#clic_sape_core:
#    resource: "@ClicSapeCoreBundle/Resources/config/routing.yml"
#    prefix:   /core

#clic_sape_clothe:
#    resource: "@ClicSapeClotheBundle/Resources/config/routing.yml"
#    prefix:   /

#clic_sape_user:
#    resource: "@ClicSapeUserBundle/Resources/config/routing.yml"
#    prefix:   /

