clic_sape_admin:
    resource: "@ClicSapeAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

clic_sape:
    resource: "@ClicSapeClotheBundle/Resources/config/routing.yml"
    prefix:   /

clic_sape_log:
    resource: "@ClicSapeUserBundle/Resources/config/routing.yml"
    prefix:   /log
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
