security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
            ROLE_ADMIN:       ROLE_USER
            ROLE_SUPER_ADMIN: ROLE_ADMIN
        
    providers:
        in_memory:
            memory: ~
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
#        dev:
#            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
#            security: false
            
        admin:
            pattern: ^/admin
            form_login:
                provider: fos_userbundle
                csrf_provider: security.csrf.token_manager
                remember_me:  true
                check_path: clic_sape_admin_check
                login_path: clic_sape_admin_login
                use_referer: false
                #login success
                default_target_path: clic_sape_admin_dashboard
                # login failure redirecting options (read further below)
                failure_path: clic_sape_admin_login
                failure_forward: false
            logout: 
                path: clic_sape_admin_logout
                target: clic_sape_admin_login
            anonymous: ~
            
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: security.csrf.token_manager
                remember_me:  true
                check_path: login_check
                login_path: login
                #login success
                always_use_default_target_path: false
                default_target_path:            index
                use_referer:                    false
                # login failure redirecting options (read further below)
                failure_path:    login
                failure_forward: false
            logout:
                path: logout
            anonymous:    true
            
    access_control:
        
        - { path: ^/[^admin], role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_ADMIN }
        
        