security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
        
    providers:
        in_memory:
            memory: ~
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: security.csrf.token_manager
                remember_me:  true
                check_path: /login_check
                login_path: /log/
                #login success
                always_use_default_target_path: false
                default_target_path:            /
                target_path_parameter:          _target_path
                use_referer:                    false
                # login failure redirecting options (read further below)
                failure_path:    /log/
                failure_forward: false
                failure_path_parameter: _failure_path

            logout:       true
            anonymous:    true
        
            
    access_control:
        - { path: ^/log/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: IS_AUTHENTICATED_ANONYMOUSLY }
