# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    

services:
    
    # Form Type #
    
    clic_sape_clothe.form.type.gender:
        class: ClicSape\Bundle\ClotheBundle\Form\Type\GenderType
        tags:
            - { name: form.type, alias: gender_type}
    clic_sape_clothe.form.type.size:
        class: ClicSape\Bundle\ClotheBundle\Form\Type\SizeType
        tags:
            - { name: form.type, alias: size_type}
    clic_sape_clothe.form.type.gamme:
        class: ClicSape\Bundle\ClotheBundle\Form\Type\GammeType
        tags:
            - { name: form.type, alias: gamme_type}
    clic_sape_clothe.form.type.category:
        class: ClicSape\Bundle\ClotheBundle\Form\Type\CategoryType
        tags:
            - { name: form.type, alias: category_type}
    clic_sape_clothe.form.type.grousize:
        class: ClicSape\Bundle\ClotheBundle\Form\Type\GroupSizeType
        tags:
            - { name: form.type, alias: groupsize_type}
    clic_sape_core.form.type.country:
        class: ClicSape\Bundle\CoreBundle\Form\Type\CountryType
        tags:
            - { name: form.type, alias: country_type}
    clic_sape_clothe.form.type.article:
        class: ClicSape\Bundle\ClotheBundle\Form\Type\ArticleType
        tags:
            - { name: form.type, alias: article_type}
    clic_sape_clothe.form.type.article_info:
        class: ClicSape\Bundle\ClotheBundle\Form\Type\ArticleInfoType
        tags:
            - { name: form.type, alias: article_info_type}
    clic_sape_core.form.type.picture:
        class: ClicSape\Bundle\CoreBundle\Form\Type\PictureType
        tags:
            - { name: form.type, alias: picture_type}
    clic_sape_Adin.twig.admin_extension:
        class: ClicSape\Bundle\AdminBundle\Twig\AdminExtension
        tags:
            - { name: twig.extension }        
    
    # Manager and repository to manipulate entity #
    
    article_repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - ClicSape\Bundle\ClotheBundle\Entity\Article
    
    article_manager:
        class:   ClicSape\Bundle\ClotheBundle\Services\ArticleService
        arguments:
            - "@article_repository"
            
    category_repository:
            class: Doctrine\ORM\EntityRepository
            factory_service: doctrine.orm.entity_manager
            factory_method: getRepository
            arguments:
                - ClicSape\Bundle\ClotheBundle\Entity\Category
            
    category_manager:
        class:   ClicSape\Bundle\ClotheBundle\Services\CategoryService
        arguments:
            - "@category_repository"

    picture_repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - ClicSape\Bundle\CoreBundle\Entity\Picture
            
    picture_manager:
        class:   ClicSape\Bundle\CoreBundle\Services\PictureService
        arguments:
            - "@picture_repository"
