clic_sape_admin_dashboard:
    path:     /
    defaults: { _controller: ClicSapeAdminBundle:Dashboard:dashboard }

clic_sape_admin_article:
    resource: "@ClicSapeAdminBundle/Resources/config/routing/article.yml"
    prefix:     /article

clic_sape_admin_category:
    resource: "@ClicSapeAdminBundle/Resources/config/routing/category.yml"
    prefix:     /category
    
clic_sape_admin_groupsize:
    resource: "@ClicSapeAdminBundle/Resources/config/routing/groupsize.yml"
    prefix:     /groupsize

clic_sape_admin_country:
    resource: "@ClicSapeAdminBundle/Resources/config/routing/country.yml"
    prefix:     /country

clic_sape_admin_picture:
    resource: "@ClicSapeAdminBundle/Resources/config/routing/picture.yml"
    prefix:     /picture

clic_sape_admin_gender:
    resource: "@ClicSapeAdminBundle/Resources/config/routing/gender.yml"
    prefix:     /gender
    
clic_sape_admin_login:
    path:     /login
    defaults: { _controller: ClicSapeUserBundle:Default:login }

clic_sape_admin_check:
    path:   /login_check
    defaults: { _controller: ClicSapeUserBundle:Security:check }
    
clic_sape_admin_logout:
    path:   /logout
    defaults: { _controller: ClicSapeUserBundle:Security:logout }

clic_sape_admin_debug:
    path:     /debug/
    defaults: { _controller: ClicSapeAdminBundle:Debug:debug }