clic_sape_admin_article:
    resource: "@ClicSapeAdminBundle/Resources/config/routing/article.yml"
    prefix:     /article

clic_sape_admin_category:
    resource: "@ClicSapeAdminBundle/Resources/config/routing/category.yml"
    prefix:     /category
    
clic_sape_admin_groupsize:
    resource: "@ClicSapeAdminBundle/Resources/config/routing/groupsize.yml"
    prefix:     /groupsize

clic_sape_admin_country:
    resource: "@ClicSapeAdminBundle/Resources/config/routing/country.yml"
    prefix:     /country

clic_sape_admin_picture:
    resource: "@ClicSapeAdminBundle/Resources/config/routing/picture.yml"
    prefix:     /picture

clic_sape_admin_gender:
    resource: "@ClicSapeAdminBundle/Resources/config/routing/gender.yml"
    prefix:     /gender
