<?php

namespace ClicSape\Bundle\OrderBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CartLineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartLineRepository extends EntityRepository
{
}
